### PR TITLE
Add sentence to instructions to titanic exercise 4 to help people cre…

### PR DESCRIPTION
**Pull request by geanders**
…ate code that will match swirl output

For this part of the question, I was trying it out, and you get marked "incorrect" if you calculate `perc_survived` as `100 * mean(Survived)` rather than `100 * survivors / N`. These two methods should create essentially the same dataset, I think there's just an occasional difference at some very far out significant digit between the two. For now, I've added to the exercise instructions that they should use the created columns `survivors` and `N` to calculate `perc_survived`. In the future, maybe we want to change this question so their final output for `perc_survived` is rounded, in which case you'd be scored "correct" with either of the two methods mentioned above.

### CODE REVIEW

**Comment by geanders** [comment]
Also, just to be clear, if you keep the option to check data frames for equality (commit 3f6084f), we would not need to add the sentence to the instructions (commit 5c4a038).

**Comment by seankross** [comment]
This looks good to me, @geanders do you want me to merge this?

**Comment by geanders** [comment]
If you like the code for rounding before checking, we won't need the extra sentence in the instructions, so let me take that out and update the pull request before you merge.

**Comment by geanders** [comment]
Alright, it's ready to merge now.

**Pull request merged**
